import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Activity,Bot,Boxes,CheckCircle2,FileCheck,GitPullRequestArrow,LayoutDashboard,Network,ScrollText,ShieldAlert,ShieldCheck,SlidersHorizontal}from'lucide-react';import'./styles.css';
const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000';type Route='dashboard'|'findings'|'assets'|'remediation'|'virtual'|'agentic'|'policies'|'reports'|'audit'|'ops';
const nav=[['dashboard','Dashboard',LayoutDashboard],['findings','Findings',ShieldAlert],['assets','Assets',Boxes],['remediation','Remediation',GitPullRequestArrow],['virtual','Virtual Patch',ShieldCheck],['agentic','Agentic',Bot],['policies','Policies',SlidersHorizontal],['reports','Reports',FileCheck],['audit','Audit',ScrollText],['ops','Operations',Activity]] as const;
async function api(path:string,options?:RequestInit){const r=await fetch(`${API}${path}`,{...options,headers:{'content-type':'application/json',...(options?.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.json()}function useApi(path:string,refresh=0){const[data,setData]=useState<any>(null);useEffect(()=>{api(path).then(setData).catch(console.error)},[path,refresh]);return data}
function Header(p:{eyebrow:string,title:string,description:string,children?:React.ReactNode}){return <header className="header"><div><p>{p.eyebrow}</p><h1>{p.title}</h1><span>{p.description}</span></div><div className="actions">{p.children}</div></header>}
function Metric(p:{label:string,value:any}){return <div className="panel metric"><span>{p.label}</span><strong>{p.value}</strong></div>}function Table(p:{rows:any[],columns:string[],title?:string}){return <section className="panel">{p.title&&<h2>{p.title}</h2>}<table><thead><tr>{p.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{(p.rows||[]).length===0&&<tr><td colSpan={p.columns.length}>No records yet.</td></tr>}{(p.rows||[]).map((r,i)=><tr key={r._id||i}>{p.columns.map(c=><td key={c}>{String(r[c]??'')}</td>)}</tr>)}</tbody></table></section>}
function Dashboard({refresh,bump}:Props){const d=useApi('/api/dashboard',refresh);return <><Header eyebrow="Enterprise command center" title="Dashboard" description="Risk, remediation, simulation, approval, and evidence posture."><button onClick={async()=>{await api('/api/mock-ingest',{method:'POST',body:'{}'});bump()}}>Load prototype data</button></Header><section className="grid cols-4"><Metric label="Open Findings" value={d?.counts?.open_findings??0}/><Metric label="Assets" value={d?.counts?.assets??0}/><Metric label="Actions" value={d?.counts?.remediation_actions??0}/><Metric label="Simulation Coverage" value={`${d?.risk?.simulation_coverage??0}%`}/></section><Table title="Top Findings" rows={d?.top_findings||[]} columns={['title','severity','business_risk_score','status']}/></>}
function Findings({refresh}:Props){const d=useApi('/api/findings',refresh);return <><Header eyebrow="Normalized backlog" title="Findings" description="Canonical findings after ingestion, deduplication, risk scoring, and asset mapping."/><Table rows={d?.findings||[]} columns={['title','severity','business_risk_score','source','status']}/></>}
function Assets({refresh}:Props){const d=useApi('/api/assets',refresh);return <><Header eyebrow="Asset inventory" title="Assets" description="Systems, owners, exposure, criticality, and sensitivity."/><Table rows={d?.assets||[]} columns={['name','type','environment','criticality','data_sensitivity','internet_exposure']}/></>}
function Remediation({refresh,bump}:Props){const d=useApi('/api/remediation-actions',refresh);const first=d?.actions?.[0]?._id;return <><Header eyebrow="Action queue" title="Remediation" description="Simulate, plan, approve, and evidence remediation before execution."><button disabled={!first} onClick={async()=>{await api(`/api/remediation-actions/${first}/simulate`,{method:'POST',body:'{}'});bump()}}>Simulate first</button><button disabled={!first} onClick={async()=>{await api(`/api/remediation-actions/${first}/plan`,{method:'POST',body:'{}'});bump()}}>Plan first</button><button disabled={!first} onClick={async()=>{await api(`/api/remediation-actions/${first}/workflow`,{method:'POST',body:'{}'});bump()}}>Approve first</button></Header><Table rows={d?.actions||[]} columns={['title','action_type','status','expected_risk_reduction']}/></>}
function Virtual({refresh,bump}:Props){const d=useApi('/api/virtual-patching',refresh);return <><Header eyebrow="Compensating controls" title="Virtual Patching" description="Protect exposed paths before permanent remediation is safe."><button onClick={async()=>{await api('/api/virtual-patching',{method:'POST',body:'{}'});bump()}}>Activate controls</button></Header><section className="grid cols-3"><Metric label="Candidates" value={d?.summary?.virtual_patch_candidates??0}/><Metric label="Path Breakers" value={d?.summary?.path_breaker_candidates??0}/><Metric label="Policies" value={d?.summary?.active_policies??0}/></section><Table rows={d?.candidates||[]} columns={['asset','control','score']}/></>}
function Agentic({refresh,bump}:Props){const d=useApi('/api/agentic',refresh)?.agentic;return <><Header eyebrow="Model-agnostic autonomy" title="Agentic Orchestrator" description="Plan with any LLM, SLM, gateway, or deterministic fallback while keeping execution governed."><button onClick={async()=>{await api('/api/agentic',{method:'POST',body:JSON.stringify({goal:'virtual_patch',prompt:'Plan safest next actions with virtual patching and path breakers.',dry_run:true})});bump()}}>Run agent plan</button></Header><section className="grid cols-4"><Metric label="Readiness" value={`${d?.readiness_score??0}%`}/><Metric label="Status" value={d?.status??'unknown'}/><Metric label="Tools" value={d?.tool_registry?.length??0}/><Metric label="Runs" value={d?.recent_agent_runs?.length??0}/></section><Table title="Model Providers" rows={d?.providers||[]} columns={['provider','model','configured']}/><Table title="Tool Registry" rows={d?.tool_registry||[]} columns={['name','mode','risk']}/></>}
function Policies({refresh}:Props){const d=useApi('/api/policies',refresh);return <><Header eyebrow="Governance" title="Policies" description="Freeze windows, evidence gates, virtual patches, and execution guardrails."/><Table rows={d?.policies||[]} columns={['name','policy_type','enabled','created_at']}/></>}
function Reports({refresh}:Props){const d=useApi('/api/reports',refresh);return <><Header eyebrow="Evidence" title="Reports" description="Report snapshots, agent plans, and governance exports."/><Table rows={d?.reports||[]} columns={['name','type','created_by','created_at']}/></>}
function Audit({refresh}:Props){const d=useApi('/api/audit',refresh);return <><Header eyebrow="Audit trail" title="Audit" description="Tenant-scoped audit records."/><Table rows={d?.audit||[]} columns={['actor','action','entity_type','created_at']}/></>}
function Ops({refresh,bump}:Props){const d=useApi('/api/observability',refresh);return <><Header eyebrow="Production operations" title="Operations" description="Worker runs, connector dry-runs, and observability."><button onClick={async()=>{await api('/api/workers/run',{method:'POST',body:JSON.stringify({lane:'simulation',limit:3})});bump()}}>Run worker</button></Header><pre>{JSON.stringify(d,null,2)}</pre></>}
type Props={refresh:number,bump:()=>void};const pages:Record<Route,React.ComponentType<Props>>={dashboard:Dashboard,findings:Findings,assets:Assets,remediation:Remediation,virtual:Virtual,agentic:Agentic,policies:Policies,reports:Reports,audit:Audit,ops:Ops};function App(){const[route,setRoute]=useState<Route>('dashboard');const[refresh,setRefresh]=useState(0);const Page=useMemo(()=>pages[route],[route]);return <div className="shell"><aside className="sidebar"><div className="brand"><span>R</span><strong>Remediation Twin</strong></div><nav>{nav.map(([key,label,Icon])=><button className={route===key?'active':''} key={key} onClick={()=>setRoute(key)}><Icon size={18}/>{label}</button>)}</nav></aside><main><Page refresh={refresh} bump={()=>setRefresh(v=>v+1)}/></main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
